### ISSUE TITLE
TTGO 433MHz support?

### ISSUE THREAD

**Issue by slavino** [tekk/TTGO-T-Beam-Car-Tracker#2]
Hello,
is the app&it's libraries capable of using 433MHz chip?

**Comment by tekk** [comment]
Hi, if you mean for the Lora chip, then yes, if the LPWAN in your country uses 433MHz and it's the only way to connect to TTN then yes. Otherwise I don't see a way to connect to a Lora gateway.

**Comment by tekk** [comment]
Now I found out you're from Slovakia as me. Well, in EU, Lora gateways work on 866MHz, so you will not be able to use 433MHz T-Beam. Hope it helps.

**Comment by slavino** [comment]
Thanks a lot for the answer. I mainly intended to have an isolated solution not interacting with gateways because those would be usually out of line of sight during the action - hence 433MHz frequency suited the solution better. Nevertheless I may consider to continue the implementation with 868MHz transceivers if I manage to deliver a working solution - so far lack of time and issues with transmitters.
